# Generated by Django 3.2.3 on 2021-06-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_videourl_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videourl',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='videourl',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
